name: example-basic
# This workflow represents a set of basic End-to-End tests
on:
  
  workflow_dispatch:
runs:
  using: "composite"
   # runs-on: ubuntu-latest
  steps:
    - name: Print
      run: echo "Hi"
